### PR TITLE
add Page Views

### PR DESCRIPTION
**Pull request by xdvrx1**
When we add this service, it will count every hit of this repo. And this will guide us more about the visitors each day and will indicate the total views. For me, this is very helpful both for us and for those will view this repo seeing this page views. If there is the website built from this repo, it can be simply added there too.

Screenshot (1695)

### CODE REVIEW

**Comment by SimonCropp** [comment]
what advantages does this have over https://github.com/approvals/ApprovalTests.Java/graphs/traffic ?

**Comment by xdvrx1** [comment]
this one will count every hit while in GitHub Traffic you have limited data: there is no total views there,

this was actually the answer to the same problem I encountered in GitHub Traffic, this is even much simpler compared to Google Analytics,

**Comment by SimonCropp** [comment]
from my perspective i dont need this information.

**Comment by xdvrx1** [comment]
It's a simple service to count every page hit. It does not fetch data from either Google Traffic or Google Analytics. Your visitors will benefit from it, seeing the page views per day and the total views.

You can check out the service too if there is doubt,

https://hits.seeyoufarm.com/

the development is in GitHub too:

https://github.com/gjbae1212/hit-counter

**Pull request closed without merging**
