### PR TITLE
Added pom.xmls for existing codebase

### PR DESCRIPTION
**Pull request by mpashkovskiy**
Hi!

I would like to add POMs to build the project with maven. I noticed #38 but looks like it is a huge refactoring and it will take some time. But as I would like to use the library soon in one of the projects I would like to have something before work on #38 will be done.
All the dependencies are marked as `provided`.
Looks like namespace `com.approvaltests` is not registered in OSS Repository Hosting but still I added plugins configured to publish artifacts there. So once you go through https://central.sonatype.org/pages/ossrh-guide.html it should be possible to publish artifacts with `mvn release:clean release:prepare release:perform`. 
There is also `.travis.yml` so if you register on https://travis-ci.org/ you can get your project build and publish artifacts automatically.

Matt

### CODE REVIEW

**Comment by isidore** [comment]
@emilybache  "provided"? is this the solution we've been looking for to handle the stuff like hadoop/ unit 3,4&5 and test ng?

**Comment by mpashkovskiy** [comment]
Forgot to mention that building with https://travis-ci.org/ is free.

**Comment by mpashkovskiy** [comment]
Can I anyhow help you to publish to maven OSS Repository Hosting so the library will be available for maven projects?

**Comment by emilybache** [comment]
@isidore I think the 'provided' dependency mechanism may well solve the problem with optional dependencies, I wasn't aware of it, I have to confess. I also want to get this project hosted in maven and I fully support any effort in this direction. My pull request may be too too big to swallow, as Matt points out :-) this may be a quicker way to get there.

**Comment by jakub-bochenski** [comment]
@emilybache what you actually want are "optional" dependencies: https://maven.apache.org/guides/introduction/introduction-to-optional-and-excludes-dependencies.html
This is the mechanism used to mark dependencies that should not be pulled transitively by dependant projects.

**Comment by isidore** [comment]
It's finally on maven! Thanks, optional was a huge help.

**Comment by mpashkovskiy** [comment]
glad to help

**Pull request closed without merging**
