### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by eugene70**
Fix file name that the test generates.

### CODE REVIEW

**Comment by LarsEckart** [comment]
Hello & thank you for this pull request.
Our documentation generating pipeline needs a fix but once this is working again, I see right to it and get your change merged.

**Comment by SimonCropp** [comment]
@LarsEckart this should be good to go

**Comment by LarsEckart** [comment]
@SimonCropp we don't have InPlaceOverwrite configured yet. From what I read in the documentation, one configures to use either InPlaceOverwrite or SourceTransform. It looks to me like moving from one to the other would mean we copy the contents of the source.md files into the generated md files and then just delete the source.md files?

**Comment by SimonCropp** [comment]
i can submit a pr that moves to InPlaceOverwrite. ??

**Comment by LarsEckart** [comment]
I can also try to do that and assign you as reviewer. I just figured it's a bit bigger change (removing current md files, renaming source file to md files, adding config) than updating the link here.

**Comment by SimonCropp** [comment]
ok. here are the docs https://github.com/SimonCropp/MarkdownSnippets#moving-from-sourcetransform-to-inplaceoverwrite

**Comment by eugene70** [comment]
Should I do something?

**Comment by LarsEckart** [comment]
No, all good. Your fix will be merged once I switched the markdown snippet process in the other docs :)

**Pull request merged**
