### PR TITLE
Multiple paths for reporters

### PR DESCRIPTION
**Pull request by martinsson**
Allow Reporters to suggest a list of paths of possible installation points
And MeldReporter for linux

### CODE REVIEW

**Comment by dogfoodsilo4** [comment]
Is this likely to be pulled in?  We currently can't use TortoiseDiff due to the error "cannot execute "C:\Program ".  I have tried adding escaped quote chars in a local repo, that gets past the error, but the diff tool is not instantiated.  No errors.

**Comment by martinsson** [comment]
Just to be clear about the problem being solved here. On windows it often happens that an executable is either in "Program Files" or "Program(x86) Files" or "Programs". It also happens on mac. So the programs have to bee looked for in several places. 

An alternative strategy would be to look for executables in the path. I think that's complementary, but probably sufficient.

I'd be happy to invest time in getting either functionality into master, but let's agree that its a problem worth solving first. WDYT @isidore ?

Cheers

**Comment by LarsEckart** [comment]
We should look into this PR. Using a windows machine in the cloud, we should have all we need to properly test this too.

**Comment by LarsEckart** [comment]
Solved with https://github.com/approvals/ApprovalTests.Java/commit/d362032e37ff1065259790dfcccd68073d74b68f so at least for MeldMerge we've 2 potential install locations now that we find.

**Pull request closed without merging**
